apiVersion: apps/v1
kind: Deployment
metadata:
  name: customermanagement
  labels:
    app: customermanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customermanagement
  template:
    metadata:
      labels:
        app: customermanagement
    spec:
      containers:
        - name: customermanagement
          image: wisemaninatown/customermanagement:20230307
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/pushMessages'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/pushMessages'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          env:
            - name: DEBUG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: config-dev
                  key: DEBUG_INFO
          volumeMounts:
          - mountPath: "/mnt/data"
            name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: aws-efs