apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafemanagement
  labels:
    app: cafemanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafemanagement
  template:
    metadata:
      labels:
        app: cafemanagement
    spec:
      containers:
        - name: cafemanagement
          image: wisemaninatown/cafemanagement:20230307
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
